### ISSUE TITLE
 Users can filter the list of webhooks

### ISSUE THREAD

**Issue by koladev32** [Transfa/sendhooks-monitoring#11]
**Description:**
Currently, our application lists all webhooks without any filtering options. We need to implement a filtering feature to enhance the user experience and make it easier for users to find specific webhooks. This feature will allow users to filter webhooks based on their status and creation date, and search for specific webhooks using the `externalId` and `url` fields.

**Feature Requirements:**
1. **Filter by Status:**
   - Users should be able to filter webhooks by their status (`success` or `failed`).
   
2. **Filter by Date:**
   - Users should be able to filter webhooks by their creation date. Options should include filtering by a specific date range.

3. **Search by External ID:**
   - Users should be able to search webhooks by their `externalId` field if it is provided.

4. **Search by URL:**
   - Users should be able to search webhooks by partial matches on the `url` field.

**Webhook Model:**
The current webhook model is defined as follows:

```typescript
import { Document, Schema, model } from "mongoose";

export interface Hook extends Document {
  id: string;
  url: string;
  status: "success" | "failed";
  created: Date;
  delivered?: Date;
  error?: string;
  externalId?: string;
}

const hookSchema = new Schema<Hook>({
  id: { type: String, required: true },
  url: { type: String, required: true },
  status: { type: String, enum: ["success", "failed"], required: true },
  created: { type: Date, default: Date.now, required: true },
  delivered: { type: Date },
  error: { type: String },
  externalId: { type: String },
});

export const HookModel = model<Hook>("Hook", hookSchema);
```

**Acceptance Criteria:**
- The webhooks list page should include UI components (e.g., dropdowns, date pickers, search fields) for each filterable field.
- The filtering should be performed server-side to ensure efficient querying and data retrieval.
- The UI should update dynamically to reflect the filtered results without requiring a full page reload.
- The filters should be combinable, allowing users to apply multiple criteria at once (e.g., filtering by status and date range simultaneously).

**Additional Notes:**
- Consider implementing pagination to handle large sets of filtered results.
- Ensure that the filtering functionality is performant and does not significantly degrade user experience.
- Provide clear user feedback for empty filter results (e.g., "No webhooks found for the selected criteria").

**Tasks:**
1. [ ] Design the UI components for filtering options.
2. [x] Implement server-side filtering logic in the relevant API endpoint.
3. [ ] Update the frontend to incorporate the new filtering options and handle user interactions.
4. [ ] Write unit and integration tests to ensure the feature works as expected.
5. [ ] Update documentation to include new filtering options instructions.
